### ISSUE TITLE
HTML template moved to templates folder

### ISSUE THREAD

**Issue by leicao-me** [conordewey3/Trump-Sentiment-Tracker#1]
Dear Conor,

Thank you for sharing this very interesting project. I really appreciate. 

I'd like to point it out that the HTML template need to be moved to a 'templates' folder inside the project root directory right now. It's possible that flask changes the rule, but I'm not sure.

Another issue in app.py: 
`from config import consumer_key, consumer_secret, access_token, access_token_secret`
`consumer_key = consumer_key`
`consumer_secret = consumer_secret`
`access_token = access_token`
`access_token_secret = access_token_secret`

this import doesn't work for me. Instead, I manually assign my Twitter API credentials by:

`consumer_key = 'my consumer key string'`
`consumer_secret = 'my consumer secret string'`
`access_token = 'my access token string'`
`access_token_secret = 'my access token secret'`

And also, please also put python==3 in the requirements.txt file. It did take me a while to figure out which version of python to use.

I can commit these updates for you if you are busy.

I'm looking forward to more awesome projects from you.

Cheers,
Lei

**Comment by cdeweyx** [comment]
Thanks for bringing these changes to my attention! I've moved the html file, added python to the requirements, and altered the Twitter API credentials for easier use. Feel free to let me know if I forgot anything or if there's anything you would've done differently!
